"""empty message

Revision ID: afb22b17ae2d
Revises: 2870bf0e8914
Create Date: 2023-01-12 19:16:23.489908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'afb22b17ae2d'
down_revision = '2870bf0e8914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clients_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('invoices_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['clients_id'], ['id'])
        batch_op.drop_column('users_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('invoices_ibfk_3', 'users', ['users_id'], ['id'])
        batch_op.drop_column('clients_id')

    # ### end Alembic commands ###
