"""empty message

Revision ID: d187722428e8
Revises: 46e604b07b00
Create Date: 2023-01-12 18:57:16.422699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd187722428e8'
down_revision = '46e604b07b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clients_id', sa.Integer(), nullable=False),
    sa.Column('sellers_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clients_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sellers_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoices_id', sa.Integer(), nullable=False),
    sa.Column('products_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoices_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['products_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices_details')
    op.drop_table('invoices')
    op.drop_table('products')
    # ### end Alembic commands ###
